import type { Task } from '@/pages/tasks/TasksPage/model/task-card/task-card.types';
import {
    TASK_PRIORITY,
    TASK_STATUS,
} from '@/pages/tasks/TasksPage/model/task-card/task-card.constants';

export const mockTasks: Task[] = [
    {
        id: '1',
        title: 'Review pull requests',
        description:
            'Go through all open PRs, check code style, request changes where needed, and merge approved ones. Ensure CI passes before merging.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-05-10',
        assignee: {
            id: '34',
            name: 'Dima',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['code-review', 'collaboration'],
        createdAt: '2025-01-10',
    },
    {
        id: '2',
        title: 'Fix login bug',
        description:
            'Users report occasional 500 error when submitting login form with special characters. Need to add input sanitization and improve error handling.',
        status: TASK_STATUS.IN_PROGRESS,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-04-28',
        assignee: {
            id: '12',
            name: 'Anna',
            avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
        },
        isPrivate: false,
        tags: ['bug', 'backend', 'critical'],
        createdAt: '2023-01-10',
    },
    {
        id: '3',
        title: 'Update documentation',
        description:
            'API documentation is outdated after recent changes. Update all endpoints, request/response examples, and authentication flow.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-05-20',
        assignee: {
            id: '45',
            name: 'Oleg',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['docs', 'writing'],
        createdAt: '2023-05-10',
    },
    {
        id: '4',
        title: 'Design system components',
        description:
            'Create reusable Button, Modal, and Dropdown components following Figma designs. Include dark mode support and accessibility features.',
        status: TASK_STATUS.IN_PROGRESS,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-05-05',
        assignee: {
            id: '78',
            name: 'Maria',
            avatarUrl: 'https://randomuser.me/api/portraits/women/78.jpg',
        },
        isPrivate: false,
        tags: ['ui', 'frontend', 'design-system'],
        createdAt: '2023-01-12',
    },
    {
        id: '5',
        title: 'Performance optimization',
        description:
            'LCP and FID metrics are below threshold. Optimize images, implement code splitting, and reduce main thread work.',
        status: TASK_STATUS.DONE,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-04-15',
        assignee: {
            id: '34',
            name: 'Dima',
            avatarUrl: null,
        },
        isPrivate: true,
        tags: ['performance', 'optimization'],
        createdAt: '2021-04-12',
    },
    {
        id: '6',
        title: 'Write unit tests',
        description:
            'Increase coverage for utils and services folders. Aim for at least 80% coverage. Focus on edge cases and error paths.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-05-25',
        assignee: {
            id: '90',
            name: 'Ivan',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['testing', 'quality'],
        createdAt: '2010-04-05',
    },
    {
        id: '7',
        title: 'Database migration',
        description:
            'Plan and execute migration from PostgreSQL 13 to 15. Test all queries, update connection strings, and schedule minimal downtime.',
        status: TASK_STATUS.IN_PROGRESS,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-04-30',
        assignee: {
            id: '23',
            name: 'Kateryna',
            avatarUrl: 'https://randomuser.me/api/portraits/women/23.jpg',
        },
        isPrivate: true,
        tags: ['database', 'devops', 'migration'],
        createdAt: '2019-04-12',
    },
    {
        id: '8',
        title: 'Customer feedback review',
        description:
            'Analyze recent NPS responses. Categorize feature requests and bug reports. Prepare summary for product team.',
        status: TASK_STATUS.DONE,
        priority: TASK_PRIORITY.LOW,
        deadline: '2025-04-10',
        assignee: {
            id: '56',
            name: 'Taras',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['product', 'analytics'],
        createdAt: '2021-04-23',
    },
    {
        id: '9',
        title: 'Mobile responsive fixes',
        description:
            'Fix layout issues on iPhone SE and Galaxy Fold. Adjust font sizes, spacing, and touch targets for small screens.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-05-18',
        assignee: {
            id: '34',
            name: 'Dima',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['css', 'mobile', 'responsive'],
        createdAt: '2021-05-12',
    },
    {
        id: '10',
        title: 'Security audit',
        description:
            'Run dependency vulnerability scan, check for exposed secrets, review CORS settings, and update authentication tokens rotation.',
        status: TASK_STATUS.IN_PROGRESS,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-05-12',
        assignee: {
            id: '67',
            name: 'Andriy',
            avatarUrl: 'https://randomuser.me/api/portraits/men/67.jpg',
        },
        isPrivate: true,
        tags: ['security', 'audit', 'compliance'],
        createdAt: '2017-07-25',
    },
    {
        id: '11',
        title: 'Onboarding new developer',
        description:
            'Prepare onboarding guide, set up development environment, schedule intro meetings, and assign first small tasks.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-06-01',
        assignee: {
            id: '12',
            name: 'Anna',
            avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
        },
        isPrivate: false,
        tags: ['onboarding', 'mentoring'],
        createdAt: '2026-05-28',
    },
    {
        id: '12',
        title: 'Update dependencies',
        description:
            'Check for outdated packages in package.json. Test breaking changes, update lockfile, and run full regression suite.',
        status: TASK_STATUS.DONE,
        priority: TASK_PRIORITY.LOW,
        deadline: '2025-04-05',
        assignee: {
            id: '45',
            name: 'Oleg',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['maintenance', 'npm'],
        createdAt: '2011-11-11',
    },
    {
        id: '13',
        title: 'Analytics dashboard',
        description:
            'Implement new charts for user engagement metrics. Add filters by date range and user segment. Export to CSV functionality.',
        status: TASK_STATUS.IN_PROGRESS,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-05-22',
        assignee: {
            id: '34',
            name: 'Dima',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['analytics', 'frontend', 'charts'],
        createdAt: '2023-05-10',
    },
    {
        id: '14',
        title: 'Refactor legacy code',
        description:
            'Convert callback-based code to async/await in payment module. Improve error handling and add retry logic.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-06-10',
        assignee: {
            id: '90',
            name: 'Ivan',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['refactor', 'backend'],
        createdAt: '2023-04-10',
    },
    {
        id: '15',
        title: 'Write release notes',
        description:
            'Summarize all changes for v2.5.0. Highlight new features, breaking changes, and fixed bugs. Send to marketing team.',
        status: TASK_STATUS.DONE,
        priority: TASK_PRIORITY.LOW,
        deadline: '2025-04-08',
        assignee: {
            id: '78',
            name: 'Maria',
            avatarUrl: 'https://randomuser.me/api/portraits/women/78.jpg',
        },
        isPrivate: false,
        tags: ['documentation', 'release'],
        createdAt: '2020-01-23',
    },
    {
        id: '16',
        title: 'Set up CI/CD pipeline',
        description:
            'Configure GitHub Actions for automated testing, linting, and deployment to staging. Add Slack notifications for failures.',
        status: TASK_STATUS.IN_PROGRESS,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-05-08',
        assignee: {
            id: '23',
            name: 'Kateryna',
            avatarUrl: 'https://randomuser.me/api/portraits/women/23.jpg',
        },
        isPrivate: true,
        tags: ['devops', 'ci-cd', 'automation'],
        createdAt: '2023-04-10',
    },
    {
        id: '17',
        title: 'User interview preparation',
        description:
            'Create discussion guide, recruit 5 participants, set up recording tools, and prepare incentives.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-05-30',
        assignee: {
            id: '56',
            name: 'Taras',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['ux-research', 'planning'],
        createdAt: '2024-04-10',
    },
    {
        id: '18',
        title: 'Fix accessibility issues',
        description:
            'Resolve WCAG 2.1 AA violations: missing alt text, low contrast, keyboard navigation gaps, and ARIA labels.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.HIGH,
        deadline: '2025-05-14',
        assignee: {
            id: '34',
            name: 'Dima',
            avatarUrl: null,
        },
        isPrivate: false,
        tags: ['accessibility', 'a11y', 'frontend'],
        createdAt: '2023-01-10',
    },
    {
        id: '19',
        title: 'Backup and recovery drill',
        description:
            'Test database restore from latest backup. Verify RPO and RTO. Document procedure and any issues found.',
        status: TASK_STATUS.IN_PROGRESS,
        priority: TASK_PRIORITY.MEDIUM,
        deadline: '2025-05-19',
        assignee: {
            id: '67',
            name: 'Andriy',
            avatarUrl: 'https://randomuser.me/api/portraits/men/67.jpg',
        },
        isPrivate: true,
        tags: ['backup', 'disaster-recovery'],
        createdAt: '2023-01-10',
    },
    {
        id: '20',
        title: 'Team building event',
        description:
            'Organize offsite: book venue, plan activities, arrange catering, and collect dietary preferences.',
        status: TASK_STATUS.TODO,
        priority: TASK_PRIORITY.LOW,
        deadline: '2025-06-15',
        assignee: {
            id: '12',
            name: 'Anna',
            avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
        },
        isPrivate: false,
        tags: ['team', 'event', 'planning'],
        createdAt: '2024-04-04',
    },
];
