const PROFILE_ROOT_PATH = '/profile';

export const PROFILE_ROUTE_SEGMENTS = {
    DETAILS: 'details',
    PREFERENCES: 'preferences',
    SECURITY: 'security',
} as const;

export const PROFILE_ROUTES = {
    PROFILE_PAGE: PROFILE_ROOT_PATH,

    PROFILE_DETAILS_PAGE: `${PROFILE_ROOT_PATH}/${PROFILE_ROUTE_SEGMENTS.DETAILS}`,
    PROFILE_PREFERENCES_PAGE: `${PROFILE_ROOT_PATH}/${PROFILE_ROUTE_SEGMENTS.PREFERENCES}`,
    PROFILE_SECURITY_PAGE: `${PROFILE_ROOT_PATH}/${PROFILE_ROUTE_SEGMENTS.SECURITY}`,
} as const;
