const TASKS_ROOT_PATH = '/tasks';

export const TASKS_ROUTES = {
    TASKS_PAGE: TASKS_ROOT_PATH,
    TASKS_MAP_PAGE: `${TASKS_ROOT_PATH}/map`,
    TASKS_DETAILS_PAGE: `${TASKS_ROOT_PATH}/:taskId`,
};
