name: Check Types
run-name: Check Types

on:
  pull_request:
  push:

env:
  NODE_VERSION: 22.13.1

jobs:
  check-types:
    runs-on: ubuntu-latest
    name: Check TypeScript types

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run all:check
